/**
 * Component Library Exporter
 * 
 * Exports generated UI components as complete, production-ready packages
 * for React, Vue, Svelte, and HTML/CSS frameworks.
 */

import type { GeneratedComponent } from '@/lib/generators/enhancedComponentGenerator';

type Framework = 'react' | 'vue' | 'svelte' | 'html';

/**
 * Generate index file for React component library
 */
function generateReactIndex(components: GeneratedComponent[]): string {
  const exports = components
    .map(c => {
      const componentName = c.name.replace(/\s+/g, '');
      return `export { ${componentName} } from './${componentName}';`;
    })
    .join('\n');

  return `/**
 * Component Library - React
 * Auto-generated by DesignForge AI
 */

${exports}

// Export all components as a single object
export const Components = {
${components.map(c => `  ${c.name.replace(/\s+/g, '')}`).join(',\n')}
};
`;
}

/**
 * Generate index file for Vue component library
 */
function generateVueIndex(components: GeneratedComponent[]): string {
  const imports = components
    .map(c => {
      const componentName = c.name.replace(/\s+/g, '');
      return `import ${componentName} from './${componentName}.vue';`;
    })
    .join('\n');

  const exports = components
    .map(c => `  ${c.name.replace(/\s+/g, '')}`)
    .join(',\n');

  return `/**
 * Component Library - Vue
 * Auto-generated by DesignForge AI
 */

${imports}

export {
${exports}
};

// Plugin installation (optional)
export default {
  install(app: any) {
${components.map(c => `    app.component('${c.name.replace(/\s+/g, '')}', ${c.name.replace(/\s+/g, '')});`).join('\n')}
  }
};
`;
}

/**
 * Generate index file for Svelte component library
 */
function generateSvelteIndex(components: GeneratedComponent[]): string {
  const exports = components
    .map(c => {
      const componentName = c.name.replace(/\s+/g, '');
      return `export { default as ${componentName} } from './${componentName}.svelte';`;
    })
    .join('\n');

  return `/**
 * Component Library - Svelte
 * Auto-generated by DesignForge AI
 */

${exports}
`;
}

/**
 * Generate index file for HTML/CSS library
 */
function generateHTMLIndex(components: GeneratedComponent[]): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Component Library - HTML/CSS</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="container">
    <h1>Component Library</h1>
    <p>Auto-generated by DesignForge AI</p>

${components.map(c => `    
    <section class="component-section">
      <h2>${c.name}</h2>
      <p>${c.description}</p>
      <div class="component-preview">
        ${c.code.html}
      </div>
    </section>
`).join('\n')}
  </div>
</body>
</html>`;
}

/**
 * Generate comprehensive README for component library
 */
function generateComponentREADME(framework: Framework, components: GeneratedComponent[]): string {
  const frameworkInfo: Record<Framework, { install: string; usage: string }> = {
    react: {
      install: `npm install react react-dom`,
      usage: `import { PrimaryButton } from './components';

function App() {
  return (
    <PrimaryButton onClick={() => alert('Clicked!')}>
      Click me
    </PrimaryButton>
  );
}`
    },
    vue: {
      install: `npm install vue`,
      usage: `<script setup>
import { PrimaryButton } from './components';
</script>

<template>
  <PrimaryButton @click="handleClick">
    Click me
  </PrimaryButton>
</template>`
    },
    svelte: {
      install: `npm install svelte`,
      usage: `<script>
  import { PrimaryButton } from './components';
</script>

<PrimaryButton on:click={handleClick}>
  Click me
</PrimaryButton>`
    },
    html: {
      install: `<!-- No installation required -->`,
      usage: `<link rel="stylesheet" href="styles.css">

<button class="primary-button">
  Click me
</button>`
    }
  };

  const info = frameworkInfo[framework];
  const componentList = components
    .map(c => `- **${c.name}** - ${c.description}`)
    .join('\n');

  return `# Component Library - ${framework.toUpperCase()}

Auto-generated by **DesignForge AI**

## 📦 Installation

\`\`\`bash
${info.install}
\`\`\`

## 🚀 Usage

${framework === 'html' ? `
### HTML
Include the CSS file in your HTML:

\`\`\`html
${info.usage}
\`\`\`
` : `
\`\`\`${framework === 'react' ? 'jsx' : framework}
${info.usage}
\`\`\`
`}

## 📚 Components

This library includes ${components.length} components:

${componentList}

## 🎨 Customization

All components are built with your design tokens and can be customized by:

${framework === 'html' ? `
- Editing the CSS variables in \`styles.css\`
- Adding custom classes to override styles
- Modifying component markup
` : `
- Passing props to components
- Using CSS modules or styled-components
- Extending component classes
`}

## 📖 Documentation

### Component Props

Each component accepts standard ${framework === 'html' ? 'HTML attributes' : 'props'} plus custom design system props:

${framework === 'react' ? `
\`\`\`typescript
interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
  disabled?: boolean;
  onClick?: () => void;
  children: React.ReactNode;
}
\`\`\`
` : framework === 'vue' ? `
\`\`\`typescript
interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
  disabled?: boolean;
}
\`\`\`
` : framework === 'svelte' ? `
\`\`\`typescript
export let variant: 'primary' | 'secondary' | 'outline' | 'ghost' = 'primary';
export let disabled: boolean = false;
\`\`\`
` : `
Use CSS classes to style components:
\`\`\`html
<button class="primary-button">Primary</button>
<button class="secondary-button">Secondary</button>
\`\`\`
`}

## 🛠️ Development

To use these components in your project:

1. Copy the components folder to your project
2. ${framework === 'html' ? 'Link the CSS file' : 'Import components as needed'}
3. Customize styles and behavior as required

## 📄 License

These components are generated for your project. Use them freely in your applications.

---

**Generated with ❤️ by [DesignForge AI](https://designforge.ai)**
`;
}

/**
 * Generate package.json for component library
 */
function generateComponentPackageJson(framework: Framework, projectName: string): string {
  const packageName = `${projectName.toLowerCase().replace(/\s+/g, '-')}-components-${framework}`;
  
  const dependencies: Record<Framework, Record<string, string>> = {
    react: {
      'react': '^18.2.0',
      'react-dom': '^18.2.0'
    },
    vue: {
      'vue': '^3.3.0'
    },
    svelte: {
      'svelte': '^4.0.0'
    },
    html: {}
  };

  const devDependencies: Record<Framework, Record<string, string>> = {
    react: {
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      'typescript': '^5.0.0'
    },
    vue: {
      '@vitejs/plugin-vue': '^4.0.0',
      'typescript': '^5.0.0'
    },
    svelte: {
      '@sveltejs/vite-plugin-svelte': '^2.0.0',
      'typescript': '^5.0.0'
    },
    html: {}
  };

  return JSON.stringify({
    name: packageName,
    version: '1.0.0',
    description: `${framework.toUpperCase()} component library generated by DesignForge AI`,
    main: framework === 'html' ? 'index.html' : 'index.ts',
    types: framework !== 'html' ? 'index.d.ts' : undefined,
    keywords: ['design-system', 'components', framework, 'ui', 'designforge'],
    author: 'DesignForge AI',
    license: 'MIT',
    peerDependencies: dependencies[framework],
    devDependencies: devDependencies[framework],
    exports: framework !== 'html' ? {
      '.': {
        'import': './index.ts',
        'require': './index.ts'
      }
    } : undefined
  }, null, 2);
}

/**
 * Export complete component library for a framework
 * 
 * @param components - Array of generated components
 * @param framework - Target framework
 * @param projectName - Project name for package metadata
 * @returns Object containing all files for the component library
 */
export function exportComponentLibrary(
  components: GeneratedComponent[],
  framework: Framework,
  projectName: string = 'design-system'
): Record<string, string> {
  const files: Record<string, string> = {};

  // Generate index file
  if (framework === 'react') {
    files['index.ts'] = generateReactIndex(components);
  } else if (framework === 'vue') {
    files['index.ts'] = generateVueIndex(components);
  } else if (framework === 'svelte') {
    files['index.ts'] = generateSvelteIndex(components);
  } else if (framework === 'html') {
    files['index.html'] = generateHTMLIndex(components);
    // Combine all CSS
    files['styles.css'] = components.map(c => c.code.css).join('\n\n');
  }

  // Add individual component files
  components.forEach(component => {
    const componentName = component.name.replace(/\s+/g, '');
    
    if (framework === 'react') {
      files[`${componentName}.tsx`] = component.code.react;
    } else if (framework === 'vue') {
      files[`${componentName}.vue`] = component.code.vue;
    } else if (framework === 'svelte') {
      files[`${componentName}.svelte`] = component.code.svelte;
    } else if (framework === 'html') {
      // HTML components are already in index.html and styles.css
    }
  });

  // Add README
  files['README.md'] = generateComponentREADME(framework, components);

  // Add package.json
  files['package.json'] = generateComponentPackageJson(framework, projectName);

  return files;
}

/**
 * Export components for multiple frameworks
 */
export function exportComponentLibraryMulti(
  components: GeneratedComponent[],
  frameworks: Framework[],
  projectName: string = 'design-system'
): Record<Framework, Record<string, string>> {
  const result: Record<string, Record<string, string>> = {};
  
  frameworks.forEach(framework => {
    result[framework] = exportComponentLibrary(components, framework, projectName);
  });

  return result;
}
