/**
 * CSS Variables Exporter
 * 
 * Exports design tokens as CSS custom properties (variables).
 * Supports colors, typography, and spacing tokens.
 */

import type { ColorPaletteResponse, TypographySystem } from '@/lib/types/designSystem';

/**
 * Export design tokens as CSS custom properties
 * 
 * Generates a complete CSS file with all design tokens as CSS variables
 * in the :root selector for global access.
 * 
 * @param palette - Color palette with all color tokens
 * @param typography - Typography system with fonts and scales
 * @param projectName - Name of the project (for comments)
 * @returns Formatted CSS string with all tokens
 */
export function exportCSSVariables(
  palette: ColorPaletteResponse,
  typography: TypographySystem,
  projectName: string = 'design-system'
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `/**
 * ${projectName} - Design Tokens
 * Generated by 4Corners AI
 * ${date}
 */

:root {
  /* Primary Colors */
  --color-primary: ${palette.primary.main};
  --color-primary-50: ${palette.primary.shades[50]};
  --color-primary-100: ${palette.primary.shades[100]};
  --color-primary-200: ${palette.primary.shades[200]};
  --color-primary-300: ${palette.primary.shades[300]};
  --color-primary-400: ${palette.primary.shades[400]};
  --color-primary-500: ${palette.primary.shades[500]};
  --color-primary-600: ${palette.primary.shades[600]};
  --color-primary-700: ${palette.primary.shades[700]};
  --color-primary-800: ${palette.primary.shades[800]};
  --color-primary-900: ${palette.primary.shades[900]};

  /* Secondary Colors */
  --color-secondary: ${palette.secondary.main};
  ${Object.entries(palette.secondary.shades)
    .map(([key, value]) => `--color-secondary-${key}: ${value};`)
    .join('\n  ')}

  /* Accent Colors */
  --color-accent: ${palette.accent.main};
  ${Object.entries(palette.accent.shades)
    .map(([key, value]) => `--color-accent-${key}: ${value};`)
    .join('\n  ')}

  /* Semantic Colors */
  --color-success: ${palette.semantic.success.main};
  ${Object.entries(palette.semantic.success.shades)
    .map(([key, value]) => `--color-success-${key}: ${value};`)
    .join('\n  ')}

  --color-error: ${palette.semantic.error.main};
  ${Object.entries(palette.semantic.error.shades)
    .map(([key, value]) => `--color-error-${key}: ${value};`)
    .join('\n  ')}

  --color-warning: ${palette.semantic.warning.main};
  ${Object.entries(palette.semantic.warning.shades)
    .map(([key, value]) => `--color-warning-${key}: ${value};`)
    .join('\n  ')}

  --color-info: ${palette.semantic.info.main};
  ${Object.entries(palette.semantic.info.shades)
    .map(([key, value]) => `--color-info-${key}: ${value};`)
    .join('\n  ')}

  /* Neutral Colors */
  ${Object.entries(palette.neutrals)
    .map(([key, value]) => `--color-gray-${key}: ${value};`)
    .join('\n  ')}

  /* Typography - Font Families */
  --font-heading: '${typography.fonts.heading}', sans-serif;
  --font-body: '${typography.fonts.body}', sans-serif;
  --font-mono: '${typography.fonts.mono}', monospace;

  /* Typography - Font Sizes */
  ${Object.entries(typography.scale)
    .map(([key, value]) => `--text-${key}: ${value};`)
    .join('\n  ')}

  /* Typography - Font Weights */
  ${Object.entries(typography.weights)
    .map(([key, value]) => `--font-${key}: ${value};`)
    .join('\n  ')}

  /* Typography - Line Heights */
  ${Object.entries(typography.lineHeights)
    .map(([key, value]) => `--leading-${key}: ${value};`)
    .join('\n  ')}

  /* Typography - Letter Spacing */
  ${Object.entries(typography.letterSpacing)
    .map(([key, value]) => `--tracking-${key}: ${value};`)
    .join('\n  ')}
}

/* Usage Examples:

  .heading {
    font-family: var(--font-heading);
    font-size: var(--text-4xl);
    font-weight: var(--font-bold);
    line-height: var(--leading-tight);
    color: var(--color-primary);
  }

  .body-text {
    font-family: var(--font-body);
    font-size: var(--text-base);
    line-height: var(--leading-normal);
    color: var(--color-gray-900);
  }

  .button-primary {
    background-color: var(--color-primary-600);
    color: var(--color-gray-50);
  }

  .button-primary:hover {
    background-color: var(--color-primary-700);
  }

  .alert-success {
    background-color: var(--color-success-100);
    border-color: var(--color-success-500);
    color: var(--color-success-900);
  }
*/
`.trim();
}
