/**
 * Export Package Generator
 * 
 * Creates a ZIP archive with design tokens in multiple formats.
 * Allows users to download a complete design system package.
 */

import JSZip from 'jszip';
import type { ColorPaletteResponse, TypographySystem } from '@/lib/types/designSystem';
import type { GeneratedComponent } from '@/lib/generators/enhancedComponentGenerator';
import { exportCSSVariables } from './cssExporter';
import { exportTailwindConfig } from './tailwindExporter';
import { exportFigmaTokens } from './figmaExporter';
import { exportSCSSVariables } from './scssExporter';
import { exportComponentLibrary } from './componentExporter';

/**
 * Export format options
 */
export interface ExportOptions {
  css?: boolean;
  tailwind?: boolean;
  figma?: boolean;
  scss?: boolean;
  includeComponents?: boolean;
  react?: boolean;
  vue?: boolean;
  svelte?: boolean;
  html?: boolean;
}

// Type alias for backward compatibility
export type PackageOptions = ExportOptions;

/**
 * Generate README content for the export package
 * 
 * @param projectName - Name of the project
 * @param options - Selected export formats
 * @returns Formatted README markdown string
 */
function generateREADME(projectName: string, options: ExportOptions): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const filesIncluded = [];
  if (options.css) filesIncluded.push('- `design-tokens.css` - CSS custom properties');
  if (options.tailwind) filesIncluded.push('- `tailwind.config.js` - Tailwind CSS configuration');
  if (options.figma) filesIncluded.push('- `figma-tokens.json` - Figma design tokens');
  if (options.scss) filesIncluded.push('- `_variables.scss` - SCSS variables');
  if (options.includeComponents) {
    const frameworks = [];
    if (options.react) frameworks.push('React');
    if (options.vue) frameworks.push('Vue');
    if (options.svelte) frameworks.push('Svelte');
    if (options.html) frameworks.push('HTML/CSS');
    if (frameworks.length > 0) {
      filesIncluded.push(`- \`components/\` - Production-ready UI components (${frameworks.join(', ')})`);
    }
  }

  return `# ${projectName} Design System

Generated by **4Corners AI** on ${date}

## 📦 Files Included

${filesIncluded.join('\n')}

## 🚀 Quick Start

### CSS Variables

${options.css ? `
\`\`\`html
<!-- Add to your HTML <head> -->
<link rel="stylesheet" href="design-tokens.css">
\`\`\`

\`\`\`css
/* Use in your CSS */
.button {
  background-color: var(--color-primary-600);
  color: var(--color-gray-50);
  font-family: var(--font-body);
  font-size: var(--text-base);
}
\`\`\`
` : '*CSS Variables export not included*'}

### Tailwind CSS

${options.tailwind ? `
\`\`\`bash
# Install Tailwind CSS
npm install tailwindcss

# Replace or merge with your tailwind.config.js
\`\`\`

\`\`\`jsx
// Use in your components
<button className="bg-primary-600 text-white font-body text-base">
  Click me
</button>
\`\`\`
` : '*Tailwind CSS export not included*'}

### Figma Tokens

${options.figma ? `
1. Install the [Figma Tokens plugin](https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens)
2. Open your Figma file
3. Open the Figma Tokens plugin
4. Click "Load from file"
5. Select \`figma-tokens.json\`
6. Apply tokens to your design

Your design system will be imported as Figma variables and styles.
` : '*Figma tokens export not included*'}

### SCSS Variables

${options.scss ? `
\`\`\`scss
// Import in your main SCSS file
@import 'variables';

// Use in your styles
.button {
  background-color: $color-primary-600;
  color: $color-gray-50;
  font-family: $font-body;
  font-size: $text-base;
  font-weight: $font-semibold;
}
\`\`\`
` : '*SCSS variables export not included*'}

### UI Components

${options.includeComponents ? `
Your package includes production-ready UI components in the following frameworks:

${options.react ? '- **React**: TypeScript components with full type safety' : ''}
${options.vue ? '- **Vue**: Vue 3 composition API components' : ''}
${options.svelte ? '- **Svelte**: Native Svelte components' : ''}
${options.html ? '- **HTML/CSS**: Vanilla HTML with CSS classes' : ''}

Each component library includes:
- Button variants (Primary, Secondary, Outline, Ghost)
- Card layouts (Default, Elevated, Outlined)
- Form inputs (Default, Filled) with labels and validation
- Alert components (Success, Error, Warning, Info)

\`\`\`${options.react ? 'jsx' : options.vue ? 'vue' : 'html'}
${options.react ? `// React example
import { PrimaryButton } from './components/react';

<PrimaryButton onClick={handleClick}>
  Click me
</PrimaryButton>` : options.vue ? `<!-- Vue example -->
<script setup>
import { PrimaryButton } from './components/vue';
</script>

<template>
  <PrimaryButton @click="handleClick">
    Click me
  </PrimaryButton>
</template>` : options.svelte ? `<!-- Svelte example -->
<script>
import { PrimaryButton } from './components/svelte';
</script>

<PrimaryButton on:click={handleClick}>
  Click me
</PrimaryButton>` : `<!-- HTML example -->
<button class="primary-button">
  Click me
</button>`}
\`\`\`

See \`components/README.md\` for detailed documentation.
` : '*UI components export not included*'}

## 📖 Documentation

### Color System

Your design system includes:

- **Primary Colors**: Main brand colors with shades (50-900)
- **Secondary Colors**: Supporting colors with shades (50-900)
- **Accent Colors**: Emphasis colors with shades (50-900)
- **Semantic Colors**: Success, Error, Warning, Info (with shades)
- **Neutral Colors**: Gray scale (50-900)

### Typography System

Your typography includes:

- **Font Families**: Heading, Body, and Monospace fonts
- **Font Sizes**: Modular scale from xs to 6xl
- **Font Weights**: Light to Black (300-900)
- **Line Heights**: Optimized for readability
- **Letter Spacing**: Fine control over text spacing

### Accessibility

All colors have been validated for:
- WCAG AA contrast ratio compliance
- AAA compliance where possible
- Readability on various backgrounds

## 🎨 Design Tokens

Design tokens are the visual design atoms of the design system — specifically, they are named entities that store visual design attributes. They're used in place of hard-coded values (like hex values for color or pixels for spacing) to ensure flexibility and maintainability.

### Benefits

- **Consistency**: Single source of truth for design decisions
- **Scalability**: Easy to update across entire project
- **Collaboration**: Designers and developers speak the same language
- **Efficiency**: Faster development and design iterations

## 🛠️ Integration Tips

### CSS Variables

CSS custom properties offer runtime flexibility and work in all modern browsers:

\`\`\`css
/* Override for dark mode */
@media (prefers-color-scheme: dark) {
  :root {
    --color-gray-900: #ffffff;
    --color-gray-50: #000000;
  }
}
\`\`\`

### Tailwind CSS

Extend the configuration to create custom utilities:

\`\`\`javascript
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      // Your tokens here
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
\`\`\`

### SCSS

Create mixins and functions for common patterns:

\`\`\`scss
@mixin button-variant($color) {
  background-color: $color;
  &:hover {
    background-color: darken($color, 10%);
  }
}

.button-primary {
  @include button-variant($color-primary-600);
}
\`\`\`

## 📚 Resources

- [CSS Variables (MDN)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)
- [Tailwind CSS Documentation](https://tailwindcss.com/docs)
- [Figma Tokens Plugin](https://www.figma.com/community/plugin/843461159747178978)
- [Sass Documentation](https://sass-lang.com/documentation)
- [Design Tokens W3C Community Group](https://www.w3.org/community/design-tokens/)

## 🤝 Support

If you have questions about using these design tokens, please refer to:

- [4Corners AI Documentation](https://4corners.ai/docs)
- [Design Systems Guide](https://designforge.ai/guides/design-systems)

## 📄 License

These design tokens are generated specifically for your project. Use them as you wish in your own projects.

---

**Generated with ❤️ by [4Corners AI](https://4corners.ai)**

*The AI-powered design system generator for modern web applications*
`.trim();
}

/**
 * Generate a complete export package as a ZIP file
 * 
 * Creates a ZIP archive containing design tokens in the selected formats,
 * UI components for selected frameworks, and comprehensive documentation.
 * 
 * @param palette - Color palette with all color tokens
 * @param typography - Typography system with fonts and scales
 * @param components - Generated UI components (optional)
 * @param options - Selected export formats and component frameworks
 * @param projectName - Name of the project (default: 'design-system')
 * @returns Promise resolving to a Blob containing the ZIP file
 * 
 * @example
 * ```typescript
 * const blob = await generateExportPackage(
 *   palette,
 *   typography,
 *   components,
 *   { 
 *     css: true, 
 *     tailwind: true, 
 *     includeComponents: true,
 *     react: true,
 *     vue: true
 *   },
 *   'my-awesome-project'
 * );
 * 
 * // Download the file
 * const url = URL.createObjectURL(blob);
 * const link = document.createElement('a');
 * link.href = url;
 * link.download = 'design-system.zip';
 * link.click();
 * ```
 */
export async function generateExportPackage(
  palette: ColorPaletteResponse,
  typography: TypographySystem,
  components: GeneratedComponent[] | null = null,
  options: ExportOptions,
  projectName: string = 'design-system'
): Promise<Blob> {
  const zip = new JSZip();

  // Add README file
  zip.file('README.md', generateREADME(projectName, options));

  // Add selected design token format files
  if (options.css) {
    const cssContent = exportCSSVariables(palette, typography, projectName);
    zip.file('design-tokens.css', cssContent);
  }

  if (options.tailwind) {
    const tailwindContent = exportTailwindConfig(palette, typography);
    zip.file('tailwind.config.js', tailwindContent);
  }

  if (options.figma) {
    const figmaContent = exportFigmaTokens(palette, typography);
    zip.file('figma-tokens.json', figmaContent);
  }

  if (options.scss) {
    const scssContent = exportSCSSVariables(palette, typography, projectName);
    zip.file('_variables.scss', scssContent);
  }

  // Add UI components for selected frameworks
  if (options.includeComponents && components && components.length > 0) {
    const componentFolder = zip.folder('components');
    
    if (componentFolder) {
      // Export React components
      if (options.react) {
        const reactFolder = componentFolder.folder('react');
        const reactFiles = exportComponentLibrary(components, 'react', projectName);
        
        if (reactFolder) {
          Object.entries(reactFiles).forEach(([filename, content]) => {
            reactFolder.file(filename, content);
          });
        }
      }

      // Export Vue components
      if (options.vue) {
        const vueFolder = componentFolder.folder('vue');
        const vueFiles = exportComponentLibrary(components, 'vue', projectName);
        
        if (vueFolder) {
          Object.entries(vueFiles).forEach(([filename, content]) => {
            vueFolder.file(filename, content);
          });
        }
      }

      // Export Svelte components
      if (options.svelte) {
        const svelteFolder = componentFolder.folder('svelte');
        const svelteFiles = exportComponentLibrary(components, 'svelte', projectName);
        
        if (svelteFolder) {
          Object.entries(svelteFiles).forEach(([filename, content]) => {
            svelteFolder.file(filename, content);
          });
        }
      }

      // Export HTML/CSS
      if (options.html) {
        const htmlFolder = componentFolder.folder('html');
        const htmlFiles = exportComponentLibrary(components, 'html', projectName);
        
        if (htmlFolder) {
          Object.entries(htmlFiles).forEach(([filename, content]) => {
            htmlFolder.file(filename, content);
          });
        }
      }

      // Add components README
      componentFolder.file('README.md', generateComponentsOverviewREADME(components, options));
    }
  }

  // Add package.json for npm-friendly packages
  const packageJson = {
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: `Design system tokens generated by DesignForge AI`,
    keywords: ['design-system', 'design-tokens', 'components', 'ui', 'css', 'tailwind', 'figma', 'scss'],
    author: 'DesignForge AI',
    license: 'MIT',
    main: options.css ? 'design-tokens.css' : undefined,
    files: [
      options.css && 'design-tokens.css',
      options.tailwind && 'tailwind.config.js',
      options.figma && 'figma-tokens.json',
      options.scss && '_variables.scss',
      options.includeComponents && 'components/',
      'README.md'
    ].filter(Boolean),
  };
  zip.file('package.json', JSON.stringify(packageJson, null, 2));

  // Generate and return the ZIP blob
  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });
}

/**
 * Generate overview README for components folder
 */
function generateComponentsOverviewREADME(
  components: GeneratedComponent[],
  options: ExportOptions
): string {
  const frameworks = [];
  if (options.react) frameworks.push('React');
  if (options.vue) frameworks.push('Vue');
  if (options.svelte) frameworks.push('Svelte');
  if (options.html) frameworks.push('HTML/CSS');

  const componentsByCategory = components.reduce((acc, c) => {
    if (!acc[c.category]) acc[c.category] = [];
    acc[c.category].push(c);
    return acc;
  }, {} as Record<string, GeneratedComponent[]>);

  return `# UI Component Library

This folder contains production-ready UI components in multiple frameworks: **${frameworks.join(', ')}**.

## 📚 Available Components

Total: **${components.length} component variants** across **${Object.keys(componentsByCategory).length} categories**

${Object.entries(componentsByCategory).map(([category, comps]) => `
### ${category.charAt(0).toUpperCase() + category.slice(1)}s

${comps.map(c => `- **${c.name}** - ${c.description}`).join('\n')}
`).join('\n')}

## 🚀 Framework-Specific Documentation

${frameworks.map(fw => `- [\`${fw.toLowerCase()}/README.md\`](./${fw.toLowerCase()}/README.md) - ${fw} usage guide`).join('\n')}

## 💡 Usage Examples

Each framework folder contains:
- Individual component files
- \`index.ts\` or \`index.html\` entry point
- \`package.json\` with dependencies
- Framework-specific README with examples

## 🎨 Design Tokens Integration

All components are built using your design system tokens and automatically adapt to:
- Primary, secondary, and accent colors
- Typography scale and font families
- Spacing and sizing system
- Semantic colors (success, error, warning, info)

## 📦 Installation

Copy the framework folder you need into your project, or install as a package:

\`\`\`bash
# Example: Using React components
cd components/react
npm install
\`\`\`

---

**Auto-generated by DesignForge AI**
`;
}

/**
 * Helper function to trigger download of the export package
 * 
 * @param blob - ZIP file blob
 * @param filename - Desired filename (default: 'design-system.zip')
 */
export function downloadExportPackage(blob: Blob, filename: string = 'design-system.zip'): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
