/**
 * SCSS Variables Exporter
 * 
 * Exports design tokens as SCSS variables.
 * Compatible with Sass/SCSS preprocessor for styling.
 */

import type { ColorPaletteResponse, TypographySystem } from '@/lib/types/designSystem';

/**
 * Export design tokens as SCSS variables
 * 
 * Generates a SCSS partial file (_variables.scss) with all design tokens
 * as SCSS variables for use with Sass/SCSS preprocessor.
 * 
 * @param palette - Color palette with all color tokens
 * @param typography - Typography system with fonts and scales
 * @param projectName - Name of the project (for comments)
 * @returns Formatted SCSS string with all tokens
 */
export function exportSCSSVariables(
  palette: ColorPaletteResponse,
  typography: TypographySystem,
  projectName: string = 'design-system'
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `// _variables.scss
// ${projectName} Design Tokens
// Generated by 4Corners AI on ${date}
//
// Import this file in your main SCSS file:
// @import 'variables';

// ============================================================================
// Color Tokens
// ============================================================================

// Primary Colors
$color-primary: ${palette.primary.main};
${Object.entries(palette.primary.shades)
  .map(([key, value]) => `$color-primary-${key}: ${value};`)
  .join('\n')}

// Secondary Colors
$color-secondary: ${palette.secondary.main};
${Object.entries(palette.secondary.shades)
  .map(([key, value]) => `$color-secondary-${key}: ${value};`)
  .join('\n')}

// Accent Colors
$color-accent: ${palette.accent.main};
${Object.entries(palette.accent.shades)
  .map(([key, value]) => `$color-accent-${key}: ${value};`)
  .join('\n')}

// Semantic Colors - Success
$color-success: ${palette.semantic.success.main};
${Object.entries(palette.semantic.success.shades)
  .map(([key, value]) => `$color-success-${key}: ${value};`)
  .join('\n')}

// Semantic Colors - Error
$color-error: ${palette.semantic.error.main};
${Object.entries(palette.semantic.error.shades)
  .map(([key, value]) => `$color-error-${key}: ${value};`)
  .join('\n')}

// Semantic Colors - Warning
$color-warning: ${palette.semantic.warning.main};
${Object.entries(palette.semantic.warning.shades)
  .map(([key, value]) => `$color-warning-${key}: ${value};`)
  .join('\n')}

// Semantic Colors - Info
$color-info: ${palette.semantic.info.main};
${Object.entries(palette.semantic.info.shades)
  .map(([key, value]) => `$color-info-${key}: ${value};`)
  .join('\n')}

// Neutral Colors (Grays)
${Object.entries(palette.neutrals)
  .map(([key, value]) => `$color-gray-${key}: ${value};`)
  .join('\n')}

// ============================================================================
// Typography Tokens
// ============================================================================

// Font Families
$font-heading: '${typography.fonts.heading}', sans-serif;
$font-body: '${typography.fonts.body}', sans-serif;
$font-mono: '${typography.fonts.mono}', monospace;

// Font Sizes (Modular Scale 1.25)
${Object.entries(typography.scale)
  .map(([key, value]) => `$text-${key}: ${value};`)
  .join('\n')}

// Font Weights
${Object.entries(typography.weights)
  .map(([key, value]) => `$font-${key}: ${value};`)
  .join('\n')}

// Line Heights
${Object.entries(typography.lineHeights)
  .map(([key, value]) => `$leading-${key}: ${value};`)
  .join('\n')}

// Letter Spacing
${Object.entries(typography.letterSpacing)
  .map(([key, value]) => `$tracking-${key}: ${value};`)
  .join('\n')}

// ============================================================================
// Usage Examples
// ============================================================================

/*
.heading {
  font-family: $font-heading;
  font-size: $text-4xl;
  font-weight: $font-bold;
  line-height: $leading-tight;
  color: $color-primary;
}

.body-text {
  font-family: $font-body;
  font-size: $text-base;
  line-height: $leading-normal;
  color: $color-gray-900;
}

.button-primary {
  background-color: $color-primary-600;
  color: $color-gray-50;
  font-weight: $font-semibold;

  &:hover {
    background-color: $color-primary-700;
  }
}

.alert-success {
  background-color: $color-success-100;
  border: 1px solid $color-success-500;
  color: $color-success-900;
}
*/
`.trim();
}

