/**
 * Tailwind CSS Configuration Exporter
 * 
 * Exports design tokens as a Tailwind CSS configuration file.
 * Extends the default Tailwind theme with custom colors and typography.
 */

import type { ColorPaletteResponse, TypographySystem } from '@/lib/types/designSystem';

/**
 * Export design tokens as Tailwind CSS configuration
 * 
 * Generates a complete tailwind.config.js file that extends the default
 * Tailwind theme with custom colors, fonts, and typography scales.
 * 
 * @param palette - Color palette with all color tokens
 * @param typography - Typography system with fonts and scales
 * @returns Formatted JavaScript configuration string
 */
export function exportTailwindConfig(
  palette: ColorPaletteResponse,
  typography: TypographySystem
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Format color shades for Tailwind
  const formatShades = (shades: Record<number, string>) => {
    return JSON.stringify(shades, null, 8).replace(/\n/g, '\n        ');
  };

  return `// tailwind.config.js
// Generated by 4Corners AI on ${date}
//
// This configuration extends the default Tailwind CSS theme with
// your custom design system tokens.
//
// Usage: Replace or merge with your existing tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Primary color palette
        primary: ${formatShades(palette.primary.shades)},

        // Secondary color palette
        secondary: ${formatShades(palette.secondary.shades)},

        // Accent color palette
        accent: ${formatShades(palette.accent.shades)},

        // Semantic colors
        success: ${formatShades(palette.semantic.success.shades)},
        error: ${formatShades(palette.semantic.error.shades)},
        warning: ${formatShades(palette.semantic.warning.shades)},
        info: ${formatShades(palette.semantic.info.shades)},

        // Neutral grays
        gray: ${formatShades(palette.neutrals)},
      },

      // Font families
      fontFamily: {
        heading: ['${typography.fonts.heading}', 'sans-serif'],
        body: ['${typography.fonts.body}', 'sans-serif'],
        mono: ['${typography.fonts.mono}', 'monospace'],
      },

      // Font sizes with line heights
      fontSize: ${JSON.stringify(typography.scale, null, 8).replace(/\n/g, '\n        ')},

      // Font weights
      fontWeight: ${JSON.stringify(typography.weights, null, 8).replace(/\n/g, '\n        ')},

      // Line heights
      lineHeight: ${JSON.stringify(typography.lineHeights, null, 8).replace(/\n/g, '\n        ')},

      // Letter spacing
      letterSpacing: ${JSON.stringify(typography.letterSpacing, null, 8).replace(/\n/g, '\n        ')},
    },
  },
  plugins: [],
};

/*
 * Usage Examples:
 *
 * Colors:
 *   <div className="bg-primary-600 text-white">Primary Button</div>
 *   <div className="text-error-500">Error Message</div>
 *   <div className="bg-success-100 border-success-500">Success Alert</div>
 *
 * Typography:
 *   <h1 className="font-heading text-4xl font-bold">Heading</h1>
 *   <p className="font-body text-base leading-normal">Body text</p>
 *   <code className="font-mono text-sm">Code snippet</code>
 *
 * Custom Utilities:
 *   <div className="text-2xl leading-tight tracking-wide">Custom text</div>
 */
`.trim();
}
