/**
 * Vue 3 Exporter
 * Exports design system as Vue 3 TypeScript composables
 */

import type { DesignSystem } from "./cssExporter";

/**
 * Export design system as Vue constants
 */
export function exportVueConstants(designSystem: DesignSystem): string {
  let code = `/**
 * Design System Constants
 * Generated by 4Corners AI
 * Vue 3 / TypeScript
 */

export const designSystem = {\n`;
  code += `  colors: {\n`;
  code += `    primary: {\n`;
  code += `      main: '${designSystem.colors.primary.hex}',\n`;
  code += `      shades: {\n`;
  for (const [shade, hex] of Object.entries(designSystem.colors.primary.shades)) {
    code += `        ${shade}: '${hex}',\n`;
  }
  code += `      },\n`;
  code += `    },\n`;

  code += `    secondary: {\n`;
  code += `      main: '${designSystem.colors.secondary.hex}',\n`;
  code += `      shades: {\n`;
  for (const [shade, hex] of Object.entries(designSystem.colors.secondary.shades)) {
    code += `        ${shade}: '${hex}',\n`;
  }
  code += `      },\n`;
  code += `    },\n`;

  code += `    accent: {\n`;
  code += `      main: '${designSystem.colors.accent.hex}',\n`;
  code += `      shades: {\n`;
  for (const [shade, hex] of Object.entries(designSystem.colors.accent.shades)) {
    code += `        ${shade}: '${hex}',\n`;
  }
  code += `      },\n`;
  code += `    },\n`;

  code += `    semantic: {\n`;
  code += `      success: '${designSystem.colors.semantic.success}',\n`;
  code += `      error: '${designSystem.colors.semantic.error}',\n`;
  code += `      warning: '${designSystem.colors.semantic.warning}',\n`;
  code += `      info: '${designSystem.colors.semantic.info}',\n`;
  code += `    },\n`;

  code += `    neutrals: {\n`;
  for (const [shade, hex] of Object.entries(designSystem.colors.neutrals)) {
    code += `      ${shade}: '${hex}',\n`;
  }
  code += `    },\n`;
  code += `  },\n`;

  code += `  typography: {\n`;
  code += `    heading: {\n`;
  code += `      font: '${designSystem.typography.heading.font}',\n`;
  code += `      h1: { size: '${designSystem.typography.heading.h1.size}', weight: '${designSystem.typography.heading.h1.weight}' },\n`;
  code += `      h2: { size: '${designSystem.typography.heading.h2.size}', weight: '${designSystem.typography.heading.h2.weight}' },\n`;
  code += `      h3: { size: '${designSystem.typography.heading.h3.size}', weight: '${designSystem.typography.heading.h3.weight}' },\n`;
  code += `    },\n`;
  code += `    body: {\n`;
  code += `      font: '${designSystem.typography.body.font}',\n`;
  code += `      large: { size: '${designSystem.typography.body.large.size}', weight: '${designSystem.typography.body.large.weight}' },\n`;
  code += `      regular: { size: '${designSystem.typography.body.regular.size}', weight: '${designSystem.typography.body.regular.weight}' },\n`;
  code += `      small: { size: '${designSystem.typography.body.small.size}', weight: '${designSystem.typography.body.small.weight}' },\n`;
  code += `      caption: { size: '${designSystem.typography.body.caption.size}', weight: '${designSystem.typography.body.caption.weight}' },\n`;
  code += `    },\n`;
  code += `  },\n`;

  code += `  spacing: {\n`;
  for (const [key, value] of Object.entries(designSystem.spacing)) {
    code += `    ${key}: '${value}',\n`;
  }
  code += `  },\n`;
  code += `} as const;\n\n`;

  code += `export type DesignSystem = typeof designSystem;\n`;

  return code;
}

/**
 * Export Vue composable for using design system
 */
export function exportVueComposable(designSystem: DesignSystem): string {
  let code = `import { computed } from 'vue';\n`;
  code += `import { designSystem } from './design-system';\n\n`;
  code += `export function useDesignSystem() {\n`;
  code += `  const colors = computed(() => designSystem.colors);\n`;
  code += `  const typography = computed(() => designSystem.typography);\n`;
  code += `  const spacing = computed(() => designSystem.spacing);\n\n`;
  code += `  return {\n`;
  code += `    colors,\n`;
  code += `    typography,\n`;
  code += `    spacing,\n`;
  code += `  };\n`;
  code += `}\n`;

  return code;
}

/**
 * Export complete Vue package
 */
export function exportVuePackage(designSystem: DesignSystem): {
  constants: string;
  composable: string;
} {
  return {
    constants: exportVueConstants(designSystem),
    composable: exportVueComposable(designSystem),
  };
}
