/**
 * Vue Exporter
 * Exports design system as Vue TypeScript constants and composables
 */

import type { DesignSystem } from "./cssExporter";

/**
 * Export design system as Vue constants
 */
export function exportVueConstants(designSystem: DesignSystem): string {
  const ds = designSystem as any; // Cast to bypass incomplete type definitions
  return `/**
 * Design System Constants
 * Generated by 4Corners AI
 */

export const designSystem = {
  colors: ${JSON.stringify(ds.colors || {}, null, 2)},
  typography: ${JSON.stringify(ds.typography || {}, null, 2)},
} as const;
`;
}

/**
 * Export design system as Vue composable
 */
export function exportVueHook(designSystem: DesignSystem): string {
  return `/**
 * Design System Hook
 * Generated by 4Corners AI
 */

import { designSystem } from './constants';

export function useDesignSystem() {
  return designSystem;
}
`;
}
